project_id = "sjsxjiozxwjepmshasgl"

[functions.start-interview]
verify_jwt = false

[functions.get-interview-results]
verify_jwt = false

[functions.analyze-interview]
verify_jwt = false

[functions.generate-report-pdf]
verify_jwt = false

[functions.fetch-vapi-data]
verify_jwt = false

[functions.initiate-payment]
verify_jwt = false

[functions.payment-ipn]
verify_jwt = false

[functions.process-referral]
verify_jwt = false
